import com.vanniktech.maven.publish.SonatypeHost

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14/userguide/building_java_projects.html in the Gradle documentation.
 */

group = "io.github.saths008"
version = "0.0.1"

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    alias(libs.plugins.kotlinter)

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    id("com.vanniktech.maven.publish") version "0.34.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Kotlin JUnit 5 integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)

    // This dependency is used internally, and not exposed to consumers on their own compile
    // classpath.
    implementation(libs.guava)

    implementation(libs.dropwizard.core)
    implementation(libs.classgraph)
    implementation(libs.kodein)
    testImplementation(libs.dropwizard.testing)
}

// Apply a specific Java toolchain to ease working on different environments.
java { toolchain { languageVersion = JavaLanguageVersion.of(21) } }

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

mavenPublishing {
    publishToMavenCentral(automaticRelease = true)

    signAllPublications()

    coordinates(group.toString(), "dropwizard-kodein", version.toString())

    pom {
        name = "dropwizard-kodein"
        description = "A simple library for dropwizard kodein integration"
        inceptionYear = "2025"
        url = "https://github.com/saths008/dropwizard-kodein"
        licenses {
            license {
                name = "The Apache License, Version 2.0"
                url = "https://www.apache.org/licenses/LICENSE-2.0.txt"
                distribution = "https://www.apache.org/licenses/LICENSE-2.0.txt"
            }
        }
        developers {
            developer {
                id = "saths008"
                name = "Saath Satheeshkumar"
                url = "https://github.com/saths008"
            }
        }
        scm {
            url = "https://github.com/saths008/dropwizard-kodein/"
            connection = "scm:git:git://github.com/saths008/dropwizard-kodein.git"
            developerConnection = "scm:git:ssh://git@github.com/saths008/dropwizard-kodein.git"
        }
    }
}
