/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.saath.dropwizard.kodein

import kotlin.test.Test
import kotlin.test.assertTrue

class KodeinBundleTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val classUnderTest = KodeinBundle()
        assertTrue(3 == 3, "someLibraryMethod should return 'true'")
    }
}
