name: Java Build & Publish

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Java ${{ matrix.java }}
    strategy:
      fail-fast: false
      matrix:
        java: [17, 21]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java }}

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build project
        run: ./gradlew build --no-daemon

  check-label:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    outputs:
      internal_label: ${{ steps.check.outputs.label }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for 'internal' PR label
        id: check
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const commitSha = context.sha;
            const { data: prs } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: commitSha
            });

            if (prs.length === 0) {
              core.info("No PR found for this commit.");
              return "";
            }

            const labels = prs[0].labels.map(label => label.name);
            core.info(`Labels found: ${labels.join(", ")}`);
            return labels.join(",");

  publish:
    runs-on: ubuntu-latest
    needs: [build, check-label]
    if: needs.check-label.outputs.internal_label != '' && !contains(needs.check-label.outputs.internal_label, 'internal')
    name: Publish to Maven Central (Java 17)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Publish to Maven Central
        run: ./gradlew publishToMavenCentral --info
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
